module.exports = {
    pages:{
        index:{
            entry:"./src/pages/index/index.js",
            template:"./src/pages/index/index.html",
            filename:"index.html",
        },
        problemList:{
            entry:"./src/pages/index/problemList.js",
            template:"./src/pages/problemList/problemList.html",
            filename:"problemList.html",
        },
        problem_decs:{
            entry:"./src/pages/problem_decs/problem_decs.js",
            template:"./src/pages/problem_decs/problem_decs.html",
            filename:"problem_decs.html",
        }
    }
}